import {
  Circle, Star, Heart, ThumbsUp, ThumbsDown,
  Lightbulb, Target, Wrench, Bell, Bookmark,
  Calendar, Camera, Cloud, Coffee, Compass,
  Copy, CreditCard, Database, Download, Upload,
  Edit, ExternalLink, Filter, Flag, Folder,
  Gift, Globe, Hash, Headphones, Home,
  Image, Inbox, Info, Key, Link,
  List, Lock, Unlock, Mail, Map,
  MapPin, Maximize, Mic, Monitor, Moon,
  MoreHorizontal, Music, Navigation, Package, Paperclip,
  Phone, PieChart, Pin, Power, Printer,
  Radio, Repeat, RotateCw, Save, Scissors,
  Search, Send, Server, Settings, Share2,
  ShoppingCart, Sidebar, Sliders, Smile, Speaker,
  Sun, Tag, Terminal, TrendingUp, Truck,
  Tv, Type, User, Users, Video,
  Volume2, Wifi, Wind, BarChart2,
  ClipboardList, PlayCircle, PauseCircle, Clock, CircleDot,
  AlertTriangle, XCircle, CheckCircle2, Activity, Eye,
  ShieldCheck, Zap, PenLine, Bug, Rocket,
  Ban, RefreshCw, MessageCircle, CircleAlert, CheckCheck,
  Building2, Medal, Briefcase, ListChecks, FileText, Layers,
  FileSpreadsheet, Presentation, FileDown, Film,
  FileImage, FileVideo, FileAudio,
  Smartphone, AppWindow, Globe2, Layout,
  /* 추가: PDF/실행파일/URL/문자/미팅 */
  FileType, Cog, Link2, MessageSquareText, UsersRound, HandshakeIcon,
  /* 추가: 중요도 */
  ChevronsUp, ChevronUp, Equal, ChevronDown, BookOpen,
  type LucideIcon,
} from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  'clipboard-list': ClipboardList, 'play-circle': PlayCircle, 'pause-circle': PauseCircle,
  'clock': Clock, 'circle-dot': CircleDot, 'alert-triangle': AlertTriangle,
  'x-circle': XCircle, 'check-circle-2': CheckCircle2, 'activity': Activity,
  'eye': Eye, 'shield-check': ShieldCheck, 'zap': Zap,
  'pen-line': PenLine, 'bug': Bug, 'rocket': Rocket,
  'ban': Ban, 'refresh-cw': RefreshCw, 'message-circle': MessageCircle,
  'circle-alert': CircleAlert, 'check-check': CheckCheck,
  'circle': Circle, 'star': Star, 'heart': Heart, 'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown, 'lightbulb': Lightbulb, 'target': Target,
  'wrench': Wrench, 'bell': Bell, 'bookmark': Bookmark,
  'calendar': Calendar, 'camera': Camera, 'cloud': Cloud, 'coffee': Coffee,
  'compass': Compass, 'copy': Copy, 'credit-card': CreditCard,
  'database': Database, 'download': Download, 'upload': Upload,
  'edit': Edit, 'external-link': ExternalLink, 'filter': Filter, 'flag': Flag,
  'folder': Folder, 'gift': Gift, 'globe': Globe, 'hash': Hash,
  'headphones': Headphones, 'home': Home,
  'image': Image, 'inbox': Inbox, 'info': Info, 'key': Key, 'link': Link,
  'list': List, 'lock': Lock, 'unlock': Unlock, 'mail': Mail, 'map': Map,
  'map-pin': MapPin, 'maximize': Maximize, 'mic': Mic, 'monitor': Monitor,
  'moon': Moon, 'more-horizontal': MoreHorizontal, 'music': Music,
  'navigation': Navigation, 'package': Package, 'paperclip': Paperclip,
  'phone': Phone, 'pie-chart': PieChart, 'pin': Pin, 'power': Power,
  'printer': Printer, 'radio': Radio, 'repeat': Repeat, 'rotate-cw': RotateCw,
  'save': Save, 'scissors': Scissors,
  'search': Search, 'send': Send, 'server': Server, 'settings': Settings,
  'share-2': Share2, 'shopping-cart': ShoppingCart, 'sidebar': Sidebar,
  'sliders': Sliders, 'smile': Smile, 'speaker': Speaker,
  'sun': Sun, 'tag': Tag, 'terminal': Terminal, 'trending-up': TrendingUp,
  'truck': Truck, 'tv': Tv, 'type': Type, 'user': User, 'users': Users,
  'video': Video, 'volume-2': Volume2, 'wifi': Wifi, 'wind': Wind,
  'bar-chart-2': BarChart2, 'file-text': FileText, 'briefcase': Briefcase,
  'layers': Layers, 'building-2': Building2, 'medal': Medal,
  'file-spreadsheet': FileSpreadsheet, 'presentation': Presentation,
  'file-down': FileDown, 'film': Film, 'file-image': FileImage,
  'file-video': FileVideo, 'file-audio': FileAudio,
  'smartphone': Smartphone, 'app-window': AppWindow,
  'globe-2': Globe2, 'layout': Layout,
  'list-checks': ListChecks,
  /* PDF/실행파일/URL/문자/미팅 */
  'file-type': FileType, 'cog': Cog, 'link-2': Link2,
  'message-square-text': MessageSquareText, 'users-round': UsersRound,
  'handshake': HandshakeIcon,
  /* 중요도 */
  'chevrons-up': ChevronsUp, 'chevron-up': ChevronUp,
  'equal': Equal, 'chevron-down': ChevronDown, 'book-open': BookOpen,
}

export function renderIcon(name?: string, size = 16) {
  if (!name) return <Circle size={size} />
  const Comp = ICON_MAP[name]
  return Comp ? <Comp size={size} /> : <Circle size={size} />
}
